{
 "title": "EdgeConnect Telemetry",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "db_bucket", "label": "Database Bucket", "query": "buckets() " },
   {
    "name": "ec_hostname",
    "label": "Appliance",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${db_bucket}\",\n    tag: \"hostname\",\n    predicate: (r) => true,\n)"
   },
   {
    "name": "tunnel_analysis_peer",
    "label": "Peer Tunnel to Analyze",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"${db_bucket}\",\n    tag: \"tunnel_alias\",\n    //predicate: (r) => r[\"hostname\"] == \"${ec_hostname}\" and r[\"tunnel_alias\"] !~ /^Passthrough_/,\n    predicate: (r) => r[\"hostname\"] == \"${ec_hostname}\",\n)\n"
   },
   {
    "name": "wan_labels",
    "label": "WAN Labels",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"${db_bucket}\",\n    tag: \"interface_label\",\n    predicate: (r) => r[\"hostname\"] == \"${ec_hostname}\" and r[\"lan/wan\"] == \"WAN\",\n)\n"
   },
   {
    "name": "lan_interfaces",
    "label": "LAN interfaces",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n    bucket: \"${db_bucket}\",\n    tag: \"interface_name\",\n    //predicate: (r) => true,\n    predicate: (r) => r[\"hostname\"] == \"${ec_hostname}\" and r[\"interface_label\"] == \"None\",\n)\n"
   },
   { "name": "baseline_period", "label": "Moving Average Period", "query": "30m,1h,6h,12h,1d,3d" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "This example code serves to demonstrate the possibilities in\nretrieving telemetry data from Orchestrator and EdgeConnect and\nvisuzalize it. The demo is simple to run, however, modifying\nand/or incorporating components of this work into your own solution\nrequires a greater understanding of Python, Docker, InfluxDB,\nGrafana, and Redis.\n\n\nAll of these components are not necessarily required for developing\nyour own solution as there may be pieces of data you don't need\nto collect, some additional others that you want to add,\nsubstitude alternative tools for task queuing, database, and\nvisualization or alerting needs.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"color:red;text-align:center;\">THIS DEMO IS NOT MEANT TO BE A PRODUCTION MONITORING SOLUTION</h1>"
   }
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "State (To Orch)",
   "type": "stat",
   "description": "Appliance state to Orchestrator value mapping\n\n\n0 - Unknown ( When an appliance is added to Orchestrator, it\n          is in this state )\n\n\n1 - Normal ( Appliance is reachable from Orchestrator)\n\n\n2 - Unreachable ( Appliance is unreachable from Orchestrator )\n\n\n3 - Unsupported Version ( Orchestrator does not support this version of the appliance )\n\n\n4 - Out of Synchronization ( Orchestrator's cache of appliance configuration/state is out of sync with the configuration/state on the appliance )\n\n\n5 - Synchronization in Progress ( Orchestrator is currently synchronizing appliances's configuration and state )\n",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"appliance_state\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"model\")\n  |> keep(columns: [\"_value\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"software_version\")\n  |> keep(columns: [\"_value\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Current Alarms",
   "type": "stat",
   "description": "Current alarms on the appliance. Will include alarms that may have been configured to ignore at Orchestrator level",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alarm_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"critical_alarms\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"critical\"}))\n  |> yield(name: \"critical\")\n\nfrom(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alarm_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"major_alarms\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"major\"}))\n  |> yield(name: \"major\")\n\nfrom(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alarm_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minor_alarms\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"minor\"}))\n  |> yield(name: \"minor\")\n\n  from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alarm_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"warning_alarms\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"warning\"}))\n  |> yield(name: \"warning\")"
    }
   ]
  },
  {
   "title": "Alarm History",
   "type": "timeseries",
   "description": "Alarms on the appliance over time. Will include alarms that may have been configured to ignore at Orchestrator level",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alarm_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"critical_alarms\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"critical\"}))\n  |> yield(name: \"critical\")\n\nfrom(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alarm_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"major_alarms\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"major\"}))\n  |> yield(name: \"major\")\n\nfrom(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alarm_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minor_alarms\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"minor\"}))\n  |> yield(name: \"minor\")\n\n  from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alarm_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"warning_alarms\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"warning\"}))\n  |> yield(name: \"warning\")"
    }
   ]
  },
  {
   "title": "Reachability (To Orch)",
   "type": "stat",
   "description": "Appliance reachability to Orchestrator value mapping\n\n\n0 – Unknown\n\n\n1 - Orchestrator talks to appliance using HTTP/HTTPS using user id and password. This is not used for EdgeConnects and SD-WAN\n\n\n2 - Appliance connects to Orchestrator using HTTPS Websocket. Orchestrator uses this permanent connection to configure/monitor appliance. This is done because Appliance may be behind a firewall making it hard for Orchestrator to contact appliance using IP address\n\n\n4 - Orchestrator sends configuration/monitoring request to Aruba Cloud Portal which relays those requests to Appliance. Appliance sends its response to Cloud Portal which relays it back to Orchestrator\n",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"appliance_reachability\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "An appliance is either designated as a hub or spoke/mesh designated as non-hub",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"network_role\")\n  |> keep(columns: [\"_value\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"platform\")\n  |> keep(columns: [\"_value\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> keep(columns: [\"_value\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "License",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"license_display\")\n  |> keep(columns: [\"_value\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "This is the configured memory on an appliance",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_memory\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Appliance State (To Orchestrator)",
   "type": "timeseries",
   "description": "Appliance state to Orchestrator value mapping\n\n\n0 - Unknown ( When an appliance is added to Orchestrator, it\n          is in this state )\n\n\n1 - Normal ( Appliance is reachable from Orchestrator)\n\n\n2 - Unreachable ( Appliance is unreachable from Orchestrator )\n\n\n3 - Unsupported Version ( Orchestrator does not support this version of the appliance )\n\n\n4 - Out of Synchronization ( Orchestrator's cache of appliance configuration/state is out of sync with the configuration/state on the appliance )\n\n\n5 - Synchronization in Progress ( Orchestrator is currently synchronizing appliances's configuration and state )\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"appliance_state\")\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field:r._field}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Free Memory / Swap Used",
   "type": "stat",
   "description": "Memory utilization can often be high on an appliance. The thresholds are configured to values that should be monitored regarding Free Memory dropping below 256MB and Swap Used climbing above 2MB",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free_memory\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Free Memory\"}))\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_used\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Swap Used\"}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Current Route Table",
   "type": "stat",
   "description": "Current route table sizes. Two separate tables for IPv4 and IPv6, each with a limit of 30,000 routes based on current software as of 9.2",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"route_table_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_v4_routes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"v4\"}))\n  |> yield(name: \"v4\")\n\nfrom(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"route_table_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_v6_routes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"v6\"}))\n  |> yield(name: \"v6\")"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Memory utilization can often be high on an appliance. The thresholds are configured to values that should be monitored regarding Free Memory dropping below 256MB and Swap Used climbing above 2MB",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free_memory\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Free Memory\"}))\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_used\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Swap Used\"}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Route table sizes over time. Two separate tables for IPv4 and IPv6, each with a limit of 30,000 routes based on current software as of 9.2",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"route_table_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_v4_routes\" or r[\"_field\"] == \"total_v6_routes\")\n  |> map(fn: (r) => ({_value:r._value,_time:r._time, _field:r._field}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Appliance Reachability (To Orchestrator)",
   "type": "timeseries",
   "description": "Appliance reachability to Orchestrator value mapping\n\n\n0 – Unknown\n\n\n1 - Orchestrator talks to appliance using HTTP/HTTPS using user id and password. This is not used for EdgeConnects and SD-WAN\n\n\n2 - Appliance connects to Orchestrator using HTTPS Websocket. Orchestrator uses this permanent connection to configure/monitor appliance. This is done because Appliance may be behind a firewall making it hard for Orchestrator to contact appliance using IP address\n\n\n4 - Orchestrator sends configuration/monitoring request to Aruba Cloud Portal which relays those requests to Appliance. Appliance sends its response to Cloud Portal which relays it back to Orchestrator\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"appliance_reachability\")\n  |> map(fn: (r) => ({_time:r._time, _value:r._value, _field:r._field}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU Idle (only below 20%)",
   "type": "timeseries",
   "description": "CPU utilization can normally be high on an appliance. Monitoring Idle dropping overly low is indicative of resource issues. Which cpu # is most critical for functions varies by hardware platform",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_stats\")\n  // Only show CPU values for those over 95% to limit noise in graph\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_pIdle\")\n  |> filter(fn: (r) => r[\"cpu_number\"] != \"ALL\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"_field\", \"cpu_number\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "description": "Many internal directories, /var notably stores sysdumps, and other important files",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"disk_dir\"] == \"/\" or r[\"disk_dir\"] == \"/var\")\n  |> map(fn: (r) => ({_value:r._value,_time:r._time, _field:\"Directory\", disk_dir:r.disk_dir}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Total Flows",
   "type": "timeseries",
   "description": "Total Flows through an appliance, capacity of flows-per-second vary by platform. Total flows is calculated as transformation adding together created and existing flows.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flow_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flows_created\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n//group by time to isolate the values you want to sum togehter\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n//to ungroup your data provide a group without any columns\n  |> group()\n  |> rename(columns: {\"_value\":\"Flows Created\"})\n  |> yield()"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flow_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flows_exist\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n//group by time to isolate the values you want to sum togehter\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n//to ungroup your data provide a group without any columns\n  |> group()\n  |> rename(columns: {\"_value\":\"Flows Exist\"})\n  |> yield()"
    }
   ]
  },
  {
   "title": "Packets Per Second",
   "type": "timeseries",
   "description": "Average PPS calculated from minute data and divided by 60, Realtime PPS is the current PPS at the time of query based on realtime second data",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flow_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lan_rx_packets\" or r[\"_field\"] == \"lan_tx_packets\" or r[\"_field\"] == \"wan_rx_packets\" or r[\"_field\"] == \"wan_tx_packets\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> map(fn: (r) => ({r with _value: r._value / 60}))\n//group by time to isolate the values you want to sum togehter\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n//to ungroup your data provide a group without any columns\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"realtime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pps\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> yield(name: \"pps\")"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "timeseries",
   "description": "Each number code represents some sort of drops in the system – most of them are normal. Some of them are equivalent to “interface queue drops” on traditional routers. We are interested in these codes:\n\n\n8 – LAN Rx Queue Full\n\n\n18 – LAN Tx Queue Full\n\n\n19 – LAN Tx ZCI Queue Full\n\n\n31 – Wan Rx Queue Full\n\n\n53 – Wan Tx ZCI Queue Full\n\n\nDemo code currently aggregates all other drops into single code of \"Other\"",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "query": "// Each number code represents some sort of drops in the\n// system – most of them are normal. Some of them are\n// equivalent to “interface queue drops” on traditional\n// routers. We are interested in these codes:\n// 8 – LAN Rx Queue Full\n// 18 – LAN Tx Queue Full\n// 19 – LAN Tx ZCI Queue Full\n// 31 – Wan Rx Queue Full\n// 53 – Wan Tx ZCI Queue Full\n// Demo code currently aggregates all other drops into single code of \"Other\"\n\nfrom(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"drop_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"drop_count\")\n  |> filter(fn: (r) => r[\"drop_reason\"] != \"Other\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> yield(name: \"last\")\n\n"
    }
   ]
  },
  { "title": "WAN Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Aggregate WAN TX / RX",
   "type": "timeseries",
   "description": "Pulls together system-wide deployment configuration and license values alongside real transmit/receive values. Appliances with Unlimited license will not display license value on graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flow_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_rx_bytes\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n  |> group()\n  |> rename(columns: {_value: \"Data RX\"})\n  |> yield()"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flow_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_tx_bytes\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n  |> group()\n  |> rename(columns: {_value: \"Data TX\"})\n  |> yield()"
    },
    {
     "query": "RX = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_inbound_bw\")\n  |> filter(fn: (r) => r[\"interface_name\"] == \"SYSTEM\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Configured RX BW\"}))\n  |> yield(name:\"RX\")\n\nTX = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_outbound_bw\")\n  |> filter(fn: (r) => r[\"interface_name\"] == \"SYSTEM\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Configured TX BW\"}))\n|> yield(name:\"TX\")"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  // exclude showing license for Unlimited as value is irrelevent\n  |> filter(fn: (r) => r[\"_field\"] == \"license_bw\" and r._value < 1000000000)\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Bandwidth License TX\"}))"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  // exclude showing license for Unlimited as value is irrelevent\n  |> filter(fn: (r) => r[\"_field\"] == \"license_bw\" and r._value < 1000000000)\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Bandwidth License RX\"}))"
    }
   ]
  },
  {
   "title": "95th Percentile",
   "type": "stat",
   "description": "95th Percentile of real traffic inbound/outbound",
   "gridPos": { "h": 10, "w": 3, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flow_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_rx_bytes\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n  |> group()\n  |> quantile(q: 0.95)"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flow_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_tx_bytes\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n  |> group()\n  |> quantile(q: 0.95)"
    }
   ]
  },
  {
   "title": "Current WAN Utilization",
   "type": "stat",
   "description": "Max percentage utilization of real inbound/outbound compared to configured license and deployment values",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "lic = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_metadata\")\n  // exclude showing license for Unlimited as value is irrelevent\n  |> filter(fn: (r) => r[\"_field\"] == \"license_bw\" and r._value < 1000000000)\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> aggregateWindow(every:1m,fn:last)\n  |> fill(column: \"_value\", usePrevious: true)\n\n\ndatarx = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flow_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_rx_bytes\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> drop(columns: [\"flow_type\"])\n  |> aggregateWindow(every:1m,fn:last)\n  |> fill(column: \"_value\", usePrevious: true)\n\ndeprx = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_inbound_bw\")\n  |> filter(fn: (r) => r[\"interface_name\"] == \"SYSTEM\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> aggregateWindow(every:1m,fn:last)\n  |> fill(column: \"_value\", usePrevious: true)\n\n// Calculate Utilization of DataRX vs Deployment\njoin(tables:{deprx:deprx, datarx:datarx}, on:[\"_time\"])\n  |> map(fn:(r) => ({\n    \"RX Deployment\": float(v: r._value_datarx) / float(v: r._value_deprx) }))\n  |> last(column: \"RX Deployment\")\n  |> yield(name: \"inbound dep\")\n\n// Calculate Utilization of DataRX vs License\njoin(tables:{lic:lic, datarx:datarx}, on:[\"_time\"])\n  |> map(fn:(r) => ({\n    \"RX License\": float(v: r._value_datarx) / float(v: r._value_lic) }))\n  |> last(column: \"RX License\")\n  |> yield(name: \"inbound lic\")\n\ndatatx = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flow_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_tx_bytes\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> drop(columns: [\"flow_type\"])\n  |> aggregateWindow(every:1m,fn:last)\n  |> fill(column: \"_value\", usePrevious: true)\n\ndeptx = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_outbound_bw\")\n  |> filter(fn: (r) => r[\"interface_name\"] == \"SYSTEM\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> aggregateWindow(every:1m,fn:last)\n  |> fill(column: \"_value\", usePrevious: true)\n\n// Calculate Utilization of DataTX vs Deployment\njoin(tables:{deptx:deptx, datatx:datatx}, on:[\"_time\"])\n  |> map(fn:(r) => ({\n    \"TX Deployment\": float(v: r._value_datatx) / float(v: r._value_deptx) }))\n  |> last(column: \"TX Deployment\")\n  |> yield(name: \"outbound\")\n\n// Calculate Utilization of DataTX vs License\njoin(tables:{lic:lic, datatx:datatx}, on:[\"_time\"])\n  |> map(fn:(r) => ({\n    \"TX License\": float(v: r._value_datatx) / float(v: r._value_lic) }))\n  |> last(column: \"TX License\")\n  |> yield(name: \"outbound lic\")"
    }
   ]
  },
  {
   "title": "${wan_labels}",
   "type": "timeseries",
   "description": "Per-WAN Label deployment values and real inbound/outbound traffic",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 41 },
   "repeat": "wan_labels",
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_stats\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rx\" or r[\"_field\"] == \"bytes_tx\")\n  |> filter(fn: (r) => r[\"interface_label\"] =~ /^${wan_labels}/)\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])"
    },
    {
     "query": "RX = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_inbound_bw\")\n  |> filter(fn: (r) => r[\"interface_name\"] == \"SYSTEM\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Configured RX BW\"}))\n  |> yield(name:\"RX\")\n\nTX = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_outbound_bw\")\n  |> filter(fn: (r) => r[\"interface_name\"] == \"SYSTEM\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Configured TX BW\"}))\n  |> yield(name:\"TX\")"
    }
   ]
  },
  {
   "title": "Inbound Cumulative Bytes",
   "type": "bargauge",
   "description": "Cumulative bytes inbound for each WAN label within the current time period",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_stats\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rx\")\n  |> filter(fn: (r) => r[\"interface_label\"] =~ /${wan_labels:regex}/)\n  //|> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> keep(columns: [\"_value\", \"_time\", \"interface_label\"])\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Outbound Cumulative Bytes",
   "type": "bargauge",
   "description": "Cumulative bytes outbound for each WAN label within the current time period",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_stats\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_tx\")\n  |> filter(fn: (r) => r[\"interface_label\"] =~ /${wan_labels:regex}/)\n  //|> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> keep(columns: [\"_value\", \"_time\", \"interface_label\"])\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Inbound Bytes by Label",
   "type": "barchart",
   "description": "Inbound bytes per WAN label over time, help identify what labels majority of traffic were utilizing. This behavior will greatly be determined by the Business Intent Overlay configuration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_stats\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rx\")\n  |> filter(fn: (r) => r[\"interface_label\"] =~ /${wan_labels:regex}/)\n  |> keep(columns: [\"_value\", \"_time\", \"_field\", \"interface_label\"])"
    }
   ]
  },
  {
   "title": "Outbound Bytes by Label",
   "type": "barchart",
   "description": "Outbound bytes per WAN label over time, help identify what labels majority of traffic were utilizing. This behavior will greatly be determined by the Business Intent Overlay configuration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_stats\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_tx\")\n  |> filter(fn: (r) => r[\"interface_label\"] =~ /${wan_labels:regex}/)\n  |> keep(columns: [\"_value\", \"_time\", \"_field\", \"interface_label\"])"
    }
   ]
  },
  { "title": "LAN Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "${lan_interfaces}",
   "type": "timeseries",
   "description": "per-LAN interface data transmission",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "repeat": "lan_interfaces",
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_stats\")\n  |> filter(fn: (r) => r[\"traffic_type\"] == \"all_traffic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rx\" or r[\"_field\"] == \"bytes_tx\")\n  |> filter(fn: (r) => r[\"interface_name\"] =~ /^${lan_interfaces}/)\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])"
    }
   ]
  },
  { "title": "Boost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Boost",
   "type": "timeseries",
   "description": "Boost utilization as visualized in Orchestrator of real utilization, configured max on appliance, and secondary axis of time experiencing insufficient Boost ",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 75 },
   "targets": [
    {
     "query": "from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_bytes\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_configured_kbps\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"seconds_not_boosted_in_minute\")\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Total Boosted Bytes",
   "type": "stat",
   "description": "Cumulative Boosted Bytes over time window",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_bytes\")\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Time Insufficient Boost",
   "type": "stat",
   "description": "Seconds logged for insufficient Boost",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Peak Boost (Actual)",
   "type": "stat",
   "description": "Peak Boost Utilization within time window",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_bytes\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n  |> max()"
    }
   ]
  },
  {
   "title": "95th Percentile (Actual)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_bytes\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> quantile(q: 0.95)"
    }
   ]
  },
  {
   "title": "Peak Boost (% Configured)",
   "type": "stat",
   "description": "Peak Boost utilization within time period compared to configured maximum Boost value on appliance",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bytes = from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_bytes\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n\nconfigured = from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_configured_kbps\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n\n\n// Calculate Utilization of Boost\njoin(tables:{bytes:bytes, configured:configured}, on:[\"_time\"])\n  |> map(fn:(r) => ({\n    \"Utilization\": float(v: r._value_bytes) / float(v: r._value_configured) }))\n  |> max(column: \"Utilization\")"
    }
   ]
  },
  {
   "title": "95th Percentile (% Configured)",
   "type": "stat",
   "description": "95th Percentile Boost utilization within time period compared to configured maximum Boost value on appliance",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bytes = from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_bytes\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n\nconfigured = from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_configured_kbps\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n\n\n// Calculate Utilization of Boost\njoin(tables:{bytes:bytes, configured:configured}, on:[\"_time\"])\n  |> map(fn:(r) => ({\n    \"Utilization\": float(v: r._value_bytes) / float(v: r._value_configured) }))\n  |> quantile(column: \"Utilization\", q:0.95)\n  |> yield(name: \"Max Boost\")"
    }
   ]
  },
  { "title": "Overlays", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Overlay Distribution Inbound",
   "type": "piechart",
   "description": "Cumulative Inbound Bytes per Business Intent Overlay for current time period ",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_overlay_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_rx\")\n  |> group(columns: [\"_measurement\", \"_field\", \"overlay\"])\n  |> cumulativeSum()\n  |> map(fn: (r) => ({_value:r._value,_time:r._time, overlay:r.overlay}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Overlay Distribution Outbound",
   "type": "piechart",
   "description": "Cumulative Outbound Bytes per Business Intent Overlay for current time period ",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_overlay_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_tx\")\n  |> group(columns: [\"_measurement\", \"_field\", \"overlay\"])\n  |> cumulativeSum()\n  |> map(fn: (r) => ({_value:r._value,_time:r._time, overlay:r.overlay}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Tunnels General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Tunnel Counts",
   "type": "timeseries",
   "description": "Stacked sum of tunnels (by type) on appliance. \"Configured Tunnels\" would be the expected total number of active tunnels on an appliance based on state of Business Intent Overlays configuration as well as WAN labels on appliance",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 99 },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_count_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"up_overlay_sdwan_tunnels\" or r[\"_field\"] == \"up_third_party_tunnels\" or r[\"_field\"] == \"up_underlay_sdwan_tunnels\")\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_count_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"overlay_sdwan_tunnels\" or r[\"_field\"] == \"third_party_tunnels\" or r[\"_field\"] == \"underlay_sdwan_tunnels\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n  |> group()\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Tunnel Count Distribution",
   "type": "piechart",
   "description": "Current counts of tunnels (by type) on appliance. \"Configured Tunnels\" would be the expected total number of active tunnels on an appliance based on state of Business Intent Overlays configuration as well as WAN labels on appliance",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_count_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"up_overlay_sdwan_tunnels\" or r[\"_field\"] == \"up_third_party_tunnels\" or r[\"_field\"] == \"up_underlay_sdwan_tunnels\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_count_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"down_overlay_sdwan_tunnels\" or r[\"_field\"] == \"down_third_party_tunnels\" or r[\"_field\"] == \"down_underlay_sdwan_tunnels\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n  |> group()\n  |> rename(columns: {_value:\"Down Tunnels\"})\n  |> yield()"
    }
   ]
  },
  {
   "title": "Tunnel Counts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_count_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"up_overlay_sdwan_tunnels\" or r[\"_field\"] == \"up_third_party_tunnels\" or r[\"_field\"] == \"up_underlay_sdwan_tunnels\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n  |> group()\n  |> rename(columns: {_value:\"Up Tunnels\"})\n  |> yield()"
    },
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_count_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"down_overlay_sdwan_tunnels\" or r[\"_field\"] == \"down_third_party_tunnels\" or r[\"_field\"] == \"down_underlay_sdwan_tunnels\")\n//group by time to isolate the values you want to sum togehter\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum(column: \"_value\")\n//to ungroup your data provide a group without any columns\n  |> group()\n  |> rename(columns: {_value:\"Down Tunnels\"})\n  |> yield()"
    }
   ]
  },
  {
   "title": "Down Overlay Tunnels",
   "type": "table",
   "description": "Alias names of Overlay tunnels in a down state, click inspect to see full list of tunnel names. If tunnel count is too long there is likely a larger issue at hand. Overlay tunnels often consist of multiple underlay tunnels and as such would be the most critical impact as it would prohibit connectivity between sites.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 107 },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_count_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"overlay_down_tunnels\")\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Down Underlay Tunnels",
   "type": "table",
   "description": "Alias names of Underlay tunnels in a down state, click inspect to see full list of tunnel names. If tunnel count is too long there is likely a larger issue at hand",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 107 },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_count_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"underlay_down_tunnels\")\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Down Third Party Tunnels",
   "type": "table",
   "description": "Alias names of Third Party tunnels in a down state, click inspect to see full list of tunnel names. If tunnel count is too long there is likely a larger issue at hand on the WAN labels in use to get to the third parties, or the third party experiencing an issue itself",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 107 },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_count_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"third_party_down_tunnels\")\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Overlay Tunnels - Loss, Jitter, MOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 }
  },
  {
   "title": "Overlay Loss % - Pre-FEC",
   "type": "timeseries",
   "description": "Compare Packet Loss PRE Forward Error Correction on all overlay tunnels",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Loss_Pct_pre-FEC\") // and r._value > 0)\n  |> filter(fn: (r) => r[\"overlay\"] != \"underlay\" and r[\"tunnel_alias\"] !~ /Passthrough_/)\n  // Raw data is % * 100, e.g. 0.84% is stored as 84\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  |> keep(columns: [\"_value\", \"_time\", \"tunnel_alias\"])\n  \n  "
    }
   ]
  },
  {
   "title": "Overlay Out of Order Packet % - Pre-POC",
   "type": "timeseries",
   "description": "Compare Packet Loss PRE Packet Order Correction on all overlay tunnels",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Out_of_Order_Pct_pre-POC\") // and r._value > 0)\n  |> filter(fn: (r) => r[\"overlay\"] != \"underlay\" and r[\"tunnel_alias\"] !~ /Passthrough_/)\n  // Raw data is % * 100, e.g. 0.84% is stored as 84\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  |> keep(columns: [\"_value\", \"_time\", \"tunnel_alias\"])"
    }
   ]
  },
  {
   "title": "Overlay MOS - Pre-FEC",
   "type": "timeseries",
   "description": "Compare MOS Scores PRE Forward Error Correction on all overlay tunnels",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Pre_FEC_MOS_Score_(*100)\")\n  |> filter(fn: (r) => r[\"overlay\"] != \"underlay\" and r[\"tunnel_alias\"] !~ /Passthrough_/)\n  // Raw data is MOS * 100, e.g. 4 is stored as 400, similar to other percent values\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  |> keep(columns: [\"_value\", \"_time\", \"tunnel_alias\"])"
    }
   ]
  },
  {
   "title": "Overlay Loss % - Post-FEC",
   "type": "timeseries",
   "description": "Compare Packet Loss POST Forward Error Correction on all overlay tunnels. Amount of FEC to correct against underlying brown-out / black-out transports will vary based on configuration of Bonding Policy per Business Intent Overlay",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Loss_Pct_post-FEC\")\n  |> filter(fn: (r) => r[\"overlay\"] != \"underlay\" and r[\"tunnel_alias\"] !~ /Passthrough_/)\n  // Raw data is % * 100, e.g. 0.84% is stored as 84\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  |> keep(columns: [\"_value\", \"_time\", \"tunnel_alias\"])"
    }
   ]
  },
  {
   "title": "Overlay Out of Order Packet % - Post-POC",
   "type": "timeseries",
   "description": "Compare Packet Loss POST Packet Order Correction on all overlay tunnels",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Out_of_Order_Pct_post-POC\") // and r._value > 0))\n  |> filter(fn: (r) => r[\"overlay\"] != \"underlay\" and r[\"tunnel_alias\"] !~ /Passthrough_/)\n  // Raw data is % * 100, e.g. 0.84% is stored as 84\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  |> keep(columns: [\"_value\", \"_time\", \"tunnel_alias\"])"
    }
   ]
  },
  {
   "title": "Overlay MOS - Post-FEC",
   "type": "timeseries",
   "description": "Compare MOS Scores POST Forward Error Correction on all overlay tunnels. Amount of FEC to correct against underlying brown-out / black-out transports will vary based on configuration of Bonding Policy per Business Intent Overlay",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Post_FEC_MOS_Score_(*100)\")\n  |> filter(fn: (r) => r[\"overlay\"] != \"underlay\" and r[\"tunnel_alias\"] !~ /Passthrough_/)\n  // Raw data is MOS * 100, e.g. 4 is stored as 400, similar to other percent values\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  |> keep(columns: [\"_value\", \"_time\", \"tunnel_alias\"])"
    }
   ]
  },
  {
   "title": "Tunnel Analysis $tunnel_analysis_peer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 }
  },
  {
   "title": "Tunnel WAN Bytes",
   "type": "timeseries",
   "description": "Bytes transported over specific tunnel chosen in dashboard variable",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_wan_rx\" or r[\"_field\"] == \"bytes_wan_tx\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))"
    }
   ]
  },
  {
   "title": "Cumulative Tunnel Bytes",
   "type": "stat",
   "description": "Cumulative Bytes transported over specific tunnel chosen in dashboard variable",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_wan_rx\" or r[\"_field\"] == \"bytes_wan_tx\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> cumulativeSum()\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Tunnel Flows",
   "type": "timeseries",
   "description": "Bytes transported over specific tunnel chosen in dashboard variable",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TCP_flow_count\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> rename(columns: {\"_value\":\"TCP Flows\"})\n  |> yield(name: \"TCP\")\n\nfrom(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"non-TCP_flow_count\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> rename(columns: {\"_value\":\"non-TCP Flows\"})\n  |> yield(name: \"non-TCP\")"
    }
   ]
  },
  {
   "title": "Current Flows",
   "type": "stat",
   "description": "Cumulative Bytes transported over specific tunnel chosen in dashboard variable",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TCP_flow_count\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> rename(columns: {\"_value\":\"TCP Flows\"})\n  |> yield(name: \"TCP\")\n\nfrom(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"non-TCP_flow_count\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> rename(columns: {\"_value\":\"non-TCP Flows\"})\n  |> yield(name: \"non-TCP\")"
    }
   ]
  },
  {
   "title": "Tunnel Jitter",
   "type": "timeseries",
   "description": "Jitter on tunnel over time, moving average to compare against as baseline calculated every minute with a period based on dashboard variable of \"Moving Average Period\"",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "current_jitter = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Jitter_(ms)\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> keep(columns: [\"_value\", \"_time\"])\n  |> rename(columns: {\"_value\":\"Actual\"})\n  |> yield(name: \"current\")\n\nma_jitter = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n    |> filter(fn: (r) => r[\"_field\"] == \"Jitter_(ms)\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> timedMovingAverage(every: 1m, period: ${baseline_period})\n  |> keep(columns: [\"_value\", \"_time\"])\n  |> rename(columns: {\"_value\":\"Moving Average\"})\n  |> yield(\"name\": \"moving_average\")"
    }
   ]
  },
  {
   "title": "Current Tunnel Jitter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Jitter_(ms)\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tunnel Out of Order % - Pre-POC vs Post-POC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Out_of_Order_Pct_pre-POC\" or r[\"_field\"] == \"Out_of_Order_Pct_post-POC\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  // Raw data is % * 100, e.g. 0.84% is stored as 84\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Current OOO Post-POC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Out_of_Order_Pct_post-POC\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  // Raw data is % * 100, e.g. 0.84% is stored as 84\n  |> map(fn: (r) => ({r with _value: r._value / 100}))"
    }
   ]
  },
  {
   "title": "Tunnel Latency",
   "type": "timeseries",
   "description": "Latency on tunnel over time, moving average to compare against as baseline calculated every minute with a period based on dashboard variable of \"Moving Average Period\"",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "current_latency = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"min_latency\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> keep(columns: [\"_value\", \"_time\"])\n  |> rename(columns: {\"_value\":\"Actual\"})\n  |> yield(name: \"current\")\n\nma_latency = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"min_latency\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> timedMovingAverage(every: 1m, period: ${baseline_period})\n  |> keep(columns: [\"_value\", \"_time\"])\n  |> rename(columns: {\"_value\":\"Moving Average\"})\n  |> yield(\"name\": \"moving_average\")"
    }
   ]
  },
  {
   "title": "Current Tunnel Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"min_latency\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tunnel Loss % - Pre-FEC vs Post-FEC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Loss_Pct_pre-FEC\" or r[\"_field\"] == \"Loss_Pct_post-FEC\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  // Raw data is % * 100, e.g. 0.84% is stored as 84\n  |> map(fn: (r) => ({r with _value: r._value / 100}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Current Loss Post-FEC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == \"${ec_hostname}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tunnel_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Loss_Pct_post-FEC\")\n  |> filter(fn: (r) => r[\"tunnel_alias\"] == \"${tunnel_analysis_peer}\")\n  // Raw data is % * 100, e.g. 0.84% is stored as 84\n  |> map(fn: (r) => ({r with _value: r._value / 100}))"
    }
   ]
  }
 ]
}