{
 "title": "Shaper & Traffic Classes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db_bucket", "label": "Database Bucket", "query": "buckets() " },
   {
    "name": "ec_hostname",
    "label": "Appliance",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${db_bucket}\",\n    tag: \"hostname\",\n    predicate: (r) => true,\n)"
   }
  ]
 },
 "panels": [
  { "title": "$ec_hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ec_hostname" },
  {
   "title": "$ec_hostname - Traffic Class Bandwidth Utilization ",
   "type": "timeseries",
   "description": "Traffic class bytes inbound/outbound represented as a percentage of the inbound/outbound system deployment values",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "//max deployment inbound\ndeprx = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_inbound_bw\")\n  |> filter(fn: (r) => r[\"interface_name\"] == \"SYSTEM\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> aggregateWindow(every:1m,fn:last)\n  |> fill(column: \"_value\", usePrevious: true)\n\n//max deployment outbound\ndeptx = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deployment_info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wan_outbound_bw\")\n  |> filter(fn: (r) => r[\"interface_name\"] == \"SYSTEM\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> aggregateWindow(every:1m,fn:last)\n  |> fill(column: \"_value\", usePrevious: true)\n\n// inbound shaping bytes\ninbound_shaper_1 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"1\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\ninbound_shaper_2 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"2\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\ninbound_shaper_3 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"3\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\ninbound_shaper_4 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"4\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\ninbound_shaper_5 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"5\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\ninbound_shaper_6 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"6\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\ninbound_shaper_7 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"7\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\ninbound_shaper_8 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"8\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\ninbound_shaper_9 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"9\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\ninbound_shaper_10 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"10\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"inbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\n// compare inbound shaper class with inbound deployment values\nin1 = join(tables:{deprx:deprx, inbound_shaper_1:inbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 1 RX\": float(v: r._value_inbound_shaper_1) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 1 RX\"])\n  |> yield(name: \"inbound 1 %\")\n\njoin(tables:{deprx:deprx, inbound_shaper_1:inbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 2 RX\": float(v: r._value_inbound_shaper_2) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 2 RX\"])\n  |> yield(name: \"inbound 2 %\")\n\njoin(tables:{deprx:deprx, inbound_shaper_3:inbound_shaper_3}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 3 RX\": float(v: r._value_inbound_shaper_3) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 3 RX\"])\n  |> yield(name: \"inbound 3 %\")\n\njoin(tables:{deprx:deprx, inbound_shaper_1:inbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 4 RX\": float(v: r._value_inbound_shaper_4) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 4 RX\"])\n  |> yield(name: \"inbound 4 %\")\n\njoin(tables:{deprx:deprx, inbound_shaper_1:inbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 5 RX\": float(v: r._value_inbound_shaper_5) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 5 RX\"])\n  |> yield(name: \"inbound 5 %\")\n\njoin(tables:{deprx:deprx, inbound_shaper_3:inbound_shaper_3}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 6 RX\": float(v: r._value_inbound_shaper_6) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 6 RX\"])\n  |> yield(name: \"inbound 6 %\")\n\njoin(tables:{deprx:deprx, inbound_shaper_1:inbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 7 RX\": float(v: r._value_inbound_shaper_7) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 7 RX\"])\n  |> yield(name: \"inbound 7 %\")\n\njoin(tables:{deprx:deprx, inbound_shaper_1:inbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 8 RX\": float(v: r._value_inbound_shaper_8) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 8 RX\"])\n  |> yield(name: \"inbound 8 %\")\n\njoin(tables:{deprx:deprx, inbound_shaper_3:inbound_shaper_3}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 9 RX\": float(v: r._value_inbound_shaper_9) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 9 RX\"])\n  |> yield(name: \"inbound 9 %\")\n\njoin(tables:{deprx:deprx, inbound_shaper_1:inbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 10 RX\": float(v: r._value_inbound_shaper_10) / float(v: r._value_deprx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 10 RX\"])\n  |> yield(name: \"inbound 10 %\")\n\n\n// outbound shaping bytes\noutbound_shaper_1 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"1\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\noutbound_shaper_2 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"2\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\noutbound_shaper_3 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"3\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\noutbound_shaper_4 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"4\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\noutbound_shaper_5 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"5\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\noutbound_shaper_6 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"6\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\noutbound_shaper_7 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"7\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\noutbound_shaper_8 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"8\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\noutbound_shaper_9 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"9\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\noutbound_shaper_10 = from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_shaped\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n  |> filter(fn: (r) => r[\"traffic_class\"] == \"10\")\n  |> filter(fn: (r) => r[\"shaper_direction\"] == \"outbound\")  \n  |> keep(columns: [\"_value\", \"_time\",\"traffic_class\", \"shaper_direction\"])\n  |> fill(column: \"_value\", usePrevious: true)\n\n// compare outbound shaper class with outbound deployment values\njoin(tables:{deptx:deptx, outbound_shaper_1:outbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 1 TX\": float(v: r._value_outbound_shaper_1) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 1 TX\"])\n  |> yield(name: \"outbound 1 %\")\n\njoin(tables:{deptx:deptx, outbound_shaper_1:outbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 2 TX\": float(v: r._value_outbound_shaper_2) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 2 TX\"])\n  |> yield(name: \"outbound 2 %\")\n\njoin(tables:{deptx:deptx, outbound_shaper_3:outbound_shaper_3}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 3 TX\": float(v: r._value_outbound_shaper_3) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 3 TX\"])\n  |> yield(name: \"outbound 3 %\")\n\njoin(tables:{deptx:deptx, outbound_shaper_1:outbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 4 TX\": float(v: r._value_outbound_shaper_4) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 4 TX\"])\n  |> yield(name: \"outbound 4 %\")\n\njoin(tables:{deptx:deptx, outbound_shaper_1:outbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 5 TX\": float(v: r._value_outbound_shaper_5) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 5 TX\"])\n  |> yield(name: \"outbound 5 %\")\n\njoin(tables:{deptx:deptx, outbound_shaper_3:outbound_shaper_3}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 6 TX\": float(v: r._value_outbound_shaper_6) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 6 TX\"])\n  |> yield(name: \"outbound 6 %\")\n\njoin(tables:{deptx:deptx, outbound_shaper_1:outbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 7 TX\": float(v: r._value_outbound_shaper_7) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 7 TX\"])\n  |> yield(name: \"outbound 7 %\")\n\njoin(tables:{deptx:deptx, outbound_shaper_1:outbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 8 TX\": float(v: r._value_outbound_shaper_8) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 8 TX\"])\n  |> yield(name: \"outbound 8 %\")\n\njoin(tables:{deptx:deptx, outbound_shaper_3:outbound_shaper_3}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 9 TX\": float(v: r._value_outbound_shaper_9) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 9 TX\"])\n  |> yield(name: \"outbound 9 %\")\n\njoin(tables:{deptx:deptx, outbound_shaper_1:outbound_shaper_1}, on:[\"_time\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n    \"Class 10 TX\": float(v: r._value_outbound_shaper_10) / float(v: r._value_deptx)}))\n  |> keep(columns: [\"_time\", \"_value\", \"Class 10 TX\"])\n  |> yield(name: \"outbound 10 %\")\n\n\n"
    }
   ]
  },
  {
   "title": "$ec_hostname Shaper Wait",
   "type": "stat",
   "description": "95th percentile for each inbound/outbound traffic class",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"shaper_wait_time\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "$ec_hostname Shaper Drops",
   "type": "timeseries",
   "description": "95th percentile for each inbound/outbound traffic class",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${db_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] =~ /^${ec_hostname}/)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"shaper_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"shaper_dropped_expired_packets\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BLANK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "This example code serves to demonstrate the possibilities in\nretrieving telemetry data from Orchestrator and EdgeConnect and\nvisuzalize it. The demo is simple to run, however, modifying\nand/or incorporating components of this work into your own solution\nrequires a greater understanding of Python, Docker, InfluxDB,\nGrafana, and Redis.\n\n\nAll of these components are not necessarily required for developing\nyour own solution as there may be pieces of data you don't need\nto collect, some additional others that you want to add,\nsubstitude alternative tools for task queuing, database, and\nvisualization or alerting needs.",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "<h1 style=\"color:red;text-align:center;\">THIS DEMO IS NOT MEANT TO BE A PRODUCTION MONITORING SOLUTION</h1>"
     }
    }
   ]
  }
 ]
}